### PR TITLE
[APG-789] Remove everything but the description

### PR DESCRIPTION
**Pull request by bmagyar**

### CODE REVIEW

**Comment by forrest-rm** [comment]
The first PR (#1) on this branch added COLCON_IGNORE files to most of the package folders which are removed in this PR. This seems like an easier way to manage future changes and merges from upstream since we may eventually additional packages when running with a physical arm. We may just need to add COLCON_IGNORE to a few additional packages specified in apg_pick `docker/deps.dockerfile`

**Comment by bmagyar** [comment]
Reworked it, thanks for the note on the already existing COLCON_IGNORE-s, I forgot about them

**Review by forrest-rm — APPROVED** [review]

**Review by MarqRazz — COMMENTED** [review]
What about `rm_control`, `rm_driver`, `rm_example` and `rm_install`?

**Comment by forrest-rm** [comment]
> What about `rm_control`, `rm_driver`, `rm_example` and `rm_install`?

You already handled those in your last PR (#1)

**Comment by MarqRazz** [comment]
> You already handled those in your last PR (#1)

Sorry I was looking at the `main` branch`.

**Pull request merged**
